In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.tree import DecisionTreeClassifier
df = pd.read_csv("/content/covid-19 symptoms dataset (1).csv")

In [ ]:
df.head()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0    102         0    9          0          -1              0
1    102         0   10          0           0              1
2    104         0   33          1          -1              0
3    101         1   59          0           1              0
4     99         0   98          0           0              0

In [ ]:
df =df[["fever","bodyPain","age","runnyNose","diffBreath","infectionProb"]]
df

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0       102         0    9          0          -1              0
1       102         0   10          0           0              1
2       104         0   33          1          -1              0
3       101         1   59          0           1              0
4        99         0   98          0           0              0
...     ...       ...  ...        ...         ...            ...
2570     99         0   90          0           0              1
2571    100         0   53          0          -1              1
2572    101         0   44          1           0              0
2573    102         0   97          0          -1              1
2574    104         1   62          1          -1              1

[2575 rows x 6 columns]

In [ ]:
df=df.rename({'infectionProb':'covid19_result'},axis=1)
df.head()

fever  bodyPain  age  runnyNose  diffBreath  covid19_result
0    102         0    9          0          -1               0
1    102         0   10          0           0               1
2    104         0   33          1          -1               0
3    101         1   59          0           1               0
4     99         0   98          0           0               0

In [ ]:
df=df[df['covid19_result'].notnull()]
df

fever  bodyPain  age  runnyNose  diffBreath  covid19_result
0       102         0    9          0          -1               0
1       102         0   10          0           0               1
2       104         0   33          1          -1               0
3       101         1   59          0           1               0
4        99         0   98          0           0               0
...     ...       ...  ...        ...         ...             ...
2570     99         0   90          0           0               1
2571    100         0   53          0          -1               1
2572    101         0   44          1           0               0
2573    102         0   97          0          -1               1
2574    104         1   62          1          -1               1

[2575 rows x 6 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2575 entries, 0 to 2574
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   fever           2575 non-null   int64
 1   bodyPain        2575 non-null   int64
 2   age             2575 non-null   int64
 3   runnyNose       2575 non-null   int64
 4   diffBreath      2575 non-null   int64
 5   covid19_result  2575 non-null   int64
dtypes: int64(6)
memory usage: 140.8 KB


In [ ]:
at=df['diffBreath']
at

0      -1
1       0
2      -1
3       1
4       0
       ..
2570    0
2571   -1
2572    0
2573   -1
2574   -1
Name: diffBreath, Length: 2575, dtype: int64

In [ ]:
def dificult_breath(categeory,threshold):
     catregeory_map={}
     for i in range(len(categeory)):
         if categeory[i]>threshold:  
            categeory[i]=1
         else:
            categeory[i]=0  
     return categeory

In [ ]:
fe=dificult_breath(at,0)
df['diffBreath']= fe
df

fever  bodyPain  age  runnyNose  diffBreath  covid19_result
0       102         0    9          0           0               0
1       102         0   10          0           0               1
2       104         0   33          1           0               0
3       101         1   59          0           1               0
4        99         0   98          0           0               0
...     ...       ...  ...        ...         ...             ...
2570     99         0   90          0           0               1
2571    100         0   53          0           0               1
2572    101         0   44          1           0               0
2573    102         0   97          0           0               1
2574    104         1   62          1           0               1

[2575 rows x 6 columns]

In [ ]:
def data_split(data,ratio):
    np.random.seed(100)
    shuffled = np.random.permutation(len(data))
    test_data_size = int(len(data)*ratio)
    test_data_indices = shuffled[: test_data_size]
    train_data_indices = shuffled[test_data_size :]
    return data.iloc[test_data_indices], data.iloc[train_data_indices]

In [ ]:
test_data, train_data = data_split(df, 0.15)

In [ ]:
train_data

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
1498     99         1    4          0           0              1
2094     99         0   70          0          -1              0
1630    102         1   14          0           1              0
1763    100         0   82          1           0              0
1927     98         1   75          0           0              1
...     ...       ...  ...        ...         ...            ...
350     100         1   32          1           1              1
1930    102         1   14          0           0              0
79      104         1   79          1           1              0
1859    101         0   60          1           0              0
1544     99         1   53          1           1              0

[2189 rows x 6 columns]

In [ ]:
test_data


fever  bodyPain  age  runnyNose  diffBreath  infectionProb
2188     98         1   13          0           0              0
1164    100         0   19          1          -1              0
503      98         1   70          0          -1              1
65      100         0   30          1           0              0
345     102         0   92          1          -1              1
...     ...       ...  ...        ...         ...            ...
189      98         1   56          0           0              0
881     101         0   65          0           0              1
247     102         0   74          1           0              0
699     100         0   50          1           1              0
1656     99         0   97          1           1              0

[386 rows x 6 columns]

In [ ]:
x = train_data[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()

In [ ]:
x

array([[ 99,   1,   4,   0,   0],
       [ 99,   0,  70,   0,  -1],
       [102,   1,  14,   0,   1],
       ...,
       [104,   1,  79,   1,   1],
       [101,   0,  60,   1,   0],
       [ 99,   1,  53,   1,   1]])

In [ ]:
x_test= test_data[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()
x_test

array([[ 98,   1,  13,   0,   0],
       [100,   0,  19,   1,  -1],
       [ 98,   1,  70,   0,  -1],
       ...,
       [102,   0,  74,   1,   0],
       [100,   0,  50,   1,   1],
       [ 99,   0,  97,   1,   1]])

In [ ]:
y_train = train_data[['infectionProb']].to_numpy().reshape(2189, )
y_test = test_data[['infectionProb']].to_numpy().reshape(386, )

In [ ]:
y_test

array([0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,

In [ ]:
#x=df.drop("covid19_result",axis=1)
#y=df["covid19_result"]

In [ ]:
#x

In [ ]:
#y

In [ ]:
from sklearn.linear_model import LogisticRegression
clflo = LogisticRegression()
clflo.fit(x, y_train)

LogisticRegression()

In [ ]:
clflo.predict_proba([[107,1,49,1,1]])


array([[0.5504449, 0.4495551]])

In [ ]:
y_pred = clf.predict_proba(x_test)
y_pred

array([[0.50184496, 0.49815504],
       [0.4516126 , 0.5483874 ],
       [0.51381247, 0.48618753],
       [0.48082745, 0.51917255],
       [0.49494217, 0.50505783],
       [0.50715954, 0.49284046],
       [0.48691831, 0.51308169],
       [0.49928701, 0.50071299],
       [0.4738269 , 0.5261731 ],
       [0.49267625, 0.50732375],
       [0.57134734, 0.42865266],
       [0.52231597, 0.47768403],
       [0.4626585 , 0.5373415 ],
       [0.57383812, 0.42616188],
       [0.52686094, 0.47313906],
       [0.4425707 , 0.5574293 ],
       [0.47007879, 0.52992121],
       [0.57516045, 0.42483955],
       [0.50470923, 0.49529077],
       [0.47008267, 0.52991733],
       [0.4772107 , 0.5227893 ],
       [0.53187053, 0.46812947],
       [0.50061979, 0.49938021],
       [0.5720262 , 0.4279738 ],
       [0.46700459, 0.53299541],
       [0.51040373, 0.48959627],
       [0.51699115, 0.48300885],
       [0.47441351, 0.52558649],
       [0.52623147, 0.47376853],
       [0.48563584, 0.51436416],
       [0.

In [ ]:
from sklearn.metrics import log_loss
log_loss(y_test, y_pred)

0.6965662943794628

In [ ]:
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(x, y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)

print(y_pred)

[1 1 1 1 0 1 0 1 0 1 0 1 1 1 1 0 1 1 0 0 0 0 1 1 1 0 0 0 0 1 1 1 0 0 0 0 0
 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 0 1 0 1 0 0 1 1 0 1
 1 1 0 1 1 0 1 1 0 1 1 0 0 0 0 0 1 0 1 0 1 0 1 0 1 0 1 1 1 0 0 0 1 1 1 0 0
 1 0 0 1 1 1 1 1 0 0 1 1 0 1 1 1 1 0 0 1 0 0 1 1 1 0 1 1 0 1 1 0 0 1 0 1 1
 0 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0 1 0 1 1 0 0 0 0 1 1 0 1 0 0 0 0 0
 0 1 0 0 0 0 1 0 1 1 0 1 1 1 1 0 1 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 1
 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 1 1 0 1 1 1 1 0 0 0 1
 1 1 1 1 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 0 0 1
 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 1 0 1 0 1
 1 1 1 0 1 1 0 1 0 0 1 0 1 1 1 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1
 0 0 1 0 1 1 1 1 0 0 0 1 1 0 0 0]


In [ ]:
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x,y_train)

y_pred=clf.predict(x_test)

print(y_pred)

[1 1 1 1 0 1 0 1 0 1 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 1 1 0 1 1 1 0 0 0 0 0
 1 0 1 1 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 1 1 1
 1 1 0 0 0 0 1 0 1 1 1 1 0 0 1 0 1 1 1 0 1 1 1 1 1 0 1 0 0 0 1 0 1 1 1 1 1
 1 1 0 0 1 1 1 1 1 1 0 1 0 1 0 1 1 0 0 1 0 0 1 1 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 0 0 0 1 0 0 1 1 1 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1
 0 0 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 0 1 0 1 1 1 0 0 1 1 0 0 0 0 0 1 1 0 1
 0 1 1 0 0 1 0 0 1 0 0 1 1 0 1 0 1 1 1 0 0 1 1 0 0 1 1 0 0 1 1 1 1 1 1 0 1
 1 1 1 0 1 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 1 0 0 1 1 0 1 0 0 0 0 0
 1 0 1 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 0 0 0 1 0 1
 1 0 1 1 1 1 0 0 1 0 0 1 0 1 1 0 1 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1
 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x, y_train)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x)

In [ ]:
print(y_pred)

[1 0 0 ... 0 1 0]


In [ ]:
import pickle

In [ ]:
pickle.dump(clflo,open('pickel_model.pkl','wb'))

model=pickle.load(open('pickel_model.pkl','rb'))

